package day16_exception_starts;

public class ExceptionHandling_demo1 {

    public static void main(String[] args) {

        Boolean b = true;
        String s2 ="true";
        b=Boolean.parseBoolean(s2);
        System.out.println(b);
//        Integer i = 10;
//        String s ="10"; i.toString();
//
//        String s1= "aa";
//
//        i=Integer.parseInt(s1);
//         System.out.println(i);
//
//        s = "Hi , I am learning Java!";
//        System.out.println(s.length());
//        try {
//            s = null;
//            System.out.println(s.length());
//        } catch (NullPointerException nullPointerException) {
//            System.out.println("Inside catch block");
//            System.out.println(nullPointerException.getMessage());
//        } finally {
//            System.out.println("In finally block");
//        }
//        System.out.println("MAIN ENDS!..");
    }
}
